# Generated by Django 5.2.5 on 2025-08-07 18:30

from django.db import migrations

from django.db import migrations
from django.contrib.auth.models import Group

def create_user_groups(apps, schema_editor):
    """Create user role groups"""
    Group = apps.get_model('auth', 'Group')
    
    groups = [
        'Superadmin',
        'Ambassador', 
        'Volunteer',
        'Member'
    ]
    
    for group_name in groups:
        Group.objects.get_or_create(name=group_name)
        
def reverse_create_user_groups(apps, schema_editor):
    """Remove user role groups"""
    Group = apps.get_model('auth', 'Group')
    
    groups = [
        'Superadmin',
        'Ambassador',
        'Volunteer', 
        'Member'
    ]
    
    Group.objects.filter(name__in=groups).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RunPython(create_user_groups, reverse_create_user_groups),
    ]
