# Generated by Django 5.2.5 on 2025-08-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_staff_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_all_profiles', 'Can view all user profiles'), ('view_private_profiles', 'Can view private profiles'), ('edit_any_profile', 'Can edit any user profile'), ('assign_volunteers', 'Can assign volunteer role'), ('assign_ambassadors', 'Can assign ambassador role'), ('export_data', 'Can export platform data')]},
        ),
    ]
