# Generated by Django 5.2.5 on 2025-09-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_all_profiles', 'Can view all user profiles'), ('view_private_profiles', 'Can view private profiles'), ('edit_any_profile', 'Can edit any user profile'), ('assign_volunteers', 'Can assign volunteer role'), ('assign_ambassadors', 'Can assign ambassador role'), ('export_data', 'Can export platform data'), ('view_join_requests', 'Can view join requests'), ('approve_join_requests', 'Can approve join requests'), ('reject_join_requests', 'Can reject join requests'), ('manage_join_requests', 'Can manage join requests'), ('resubmit_join_request', 'Can resubmit join request')]},
        ),
    ]
