services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
      args:  
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_AUTH_HEADER_PREFIX: ${VITE_AUTH_HEADER_PREFIX}
    container_name: club-backend
    ports:
      - "9000:8000"   
    env_file:
      - ./.env
    volumes:
      - ./club_backend:/app
      - ./club_backend/media:/app/media
      - ./club_backend/staticfiles:/app/staticfiles
      - /var/www/${PROJECT_NAME:-itcomclubs}/dist:/app/frontend_dist:rw
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning/datasources
    ports:
      - "3002:3000"
    depends_on:
      - prometheus

  db:
    image: postgres:15
    container_name: club-db
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5437:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:       
  prometheus_data:
  grafana_data:
