# Generated by Django 5.2.5 on 2025-08-13 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_created_by_eventreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('manage_events', 'Can manage events'), ('create_events', 'Can create events'), ('approve_events', 'Can approve events'), ('cancel_events', 'Can cancel events')]},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'permissions': [('view_event_registrations', 'Can view event registrations'), ('manage_event_registrations', 'Can manage event registrations'), ('mark_attendance', 'Can mark event attendance'), ('view_all_registrations', 'Can view all event registrations')]},
        ),
        migrations.AlterModelOptions(
            name='eventreport',
            options={'permissions': [('view_reports', 'Can view event reports'), ('review_reports', 'Can review event reports'), ('approve_reports', 'Can approve event reports')]},
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'user')},
        ),
    ]
