# Generated by Django 5.2.5 on 2025-08-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_options_alter_eventregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(default='media/events/default_event_poster_image.png', upload_to='media/events/posters'),
        ),
    ]
