# Generated by Django 5.2.5 on 2025-10-12 09:29

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_rename_clubs_club_name_657a0c_idx_club_name_search_and_more'),
        ('events', '0005_event_poster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_club_id_7c0740_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_created_95418c_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_tag_0b0702_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='event_date_primary',
            old_name='events_even_date_5e8e1c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-date'], name='event_date_desc'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['club', 'date'], name='event_club_date'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', '-date'], name='event_creator_date'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('date__gte', datetime.datetime(2025, 10, 12, 9, 29, 16, 992601, tzinfo=datetime.timezone.utc))), fields=['date'], name='event_upcoming_only'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['club', 'created_at'], name='event_club_stats'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date', 'club'], name='event_date_club_stats'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['user', 'event'], name='registration_user_event'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'user'], name='registration_event_user'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'attended'], name='registration_event_attendance'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'created_at'], name='registration_event_date'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['user', '-created_at'], name='registration_user_recent'),
        ),
        migrations.AddIndex(
            model_name='eventreport',
            index=models.Index(fields=['submitted_by', '-submitted_at'], name='report_submitter_recent'),
        ),
        migrations.AddIndex(
            model_name='eventreport',
            index=models.Index(fields=['event'], name='report_event_lookup'),
        ),
        migrations.AddIndex(
            model_name='eventreport',
            index=models.Index(fields=['-submitted_at'], name='report_recent_all'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_registration'),
        ),
    ]
