# Generated by Django 5.2.5 on 2025-10-12 09:31

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_rename_clubs_club_name_657a0c_idx_club_name_search_and_more'),
        ('events', '0006_remove_event_events_even_club_id_7c0740_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='event_upcoming_only',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('date__gte', datetime.datetime(2025, 10, 12, 9, 31, 25, 879318, tzinfo=datetime.timezone.utc))), fields=['date'], name='event_upcoming_only'),
        ),
    ]
