# Generated by Django 5.2.5 on 2025-10-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_event_upcoming_only_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='event_upcoming_only',
        ),
    ]
