# Generated by Django 5.2.5 on 2025-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/club_logos')),
                ('club_points', models.IntegerField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['university'], name='clubs_club_univers_7b0ace_idx'), models.Index(fields=['name'], name='clubs_club_name_657a0c_idx')],
                'unique_together': {('name', 'university')},
            },
        ),
    ]
