# Generated by Django 5.2.5 on 2025-08-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'permissions': [('manage_clubs', 'Can manage clubs'), ('create_clubs', 'Can create new clubs'), ('manage_club_members', 'Can manage club members'), ('view_club_analytics', 'Can view club analytics'), ('edit_club_points', 'Can edit club points')]},
        ),
    ]
