# Generated by Django 5.2.5 on 2025-10-12 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_joinrequest_rejection_reason_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='club',
            new_name='club_name_search',
            old_name='clubs_club_name_657a0c_idx',
        ),
        migrations.RenameIndex(
            model_name='club',
            new_name='club_university_filter',
            old_name='clubs_club_univers_7b0ace_idx',
        ),
        migrations.AlterUniqueTogether(
            name='club',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['-club_points', '-created_at'], name='club_list_primary'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['university', '-club_points'], name='club_university_points'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['created_at'], name='club_created_date'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['admin'], name='club_admin_lookup'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['university', 'name'], name='club_university_name'),
        ),
        migrations.AddIndex(
            model_name='joinrequest',
            index=models.Index(fields=['club', 'status', '-created_at'], name='joinreq_club_status_date'),
        ),
        migrations.AddIndex(
            model_name='joinrequest',
            index=models.Index(fields=['status', '-created_at'], name='joinreq_status_date'),
        ),
        migrations.AddIndex(
            model_name='joinrequest',
            index=models.Index(fields=['user', 'club'], name='joinreq_user_club'),
        ),
        migrations.AddIndex(
            model_name='joinrequest',
            index=models.Index(fields=['user', 'status'], name='joinreq_user_status'),
        ),
        migrations.AddIndex(
            model_name='joinrequest',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['-created_at'], name='joinreq_pending_recent'),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('name', 'university'), name='unique_club_per_university'),
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('user', 'club'), name='unique_active_join_request'),
        ),
    ]
